[book]
authors = ["Anne Baanen", "Alexander Bentkamp", "Jasmin Blanchette", "Johannes Hölzl", "Jannis Limperg"]
language = "en"
multilingual = false
src = "."
title = "The Hitchhiker’s Guide to Logical Verification"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/leanprover/HitchikersGuide"
additional-css = ["alectryon.css", "pygments.css", "custom.css"]
additional-js = ["alectryon.js"]
mathjax-support = true

[output.html.fold]
enable = true
level = 0

[output.html.playground.boring-prefixes]
lean = "# "
